name: mdl
description: Material Design Lite for Dart
version: 2.2.2+1
author: Mike Mitterer <office@mikemitterer.at>
homepage: http://www.material-design-lite.pub

environment:
#  sdk: ">=1.8.0 <2.0.0"
  sdk: '>=2.0.0-dev.52.0 <2.0.0'

dependencies:
#  browser: ^0.10.0

  intl: ^0.15.0
  validate: ^1.0.0
  browser_detect: ^1.0.0

  logging: '>=0.11.3 <1.0.0'
  console_log_handler: '>=0.5.0 <1.0.0'

  route_hierarchical: ^0.7.0

  mustache: ^1.0.0
    #git: git://github.com/xxgreg/mustache

  dnd: ^0.4.0

#  dryice: ^1.8.3+1
  dryice:
    git:
      url: git://github.com/dudochkin-victor/dryice.git
      ref: a63ec5bdc31463267d4763f32c3272ae9cc5efa3
      
  barback: ^0.15.0

  path: ^1.4.0


#  l10n: ">=1.2.7 <2.0.0"
    # path: /Volumes/Daten/DevLocal/DevDart/L10N4Dart
  l10n:
    git:
      url: git://github.com/dudochkin-victor/dart-l10n-gettext.git
      ref: dc49e198dce90d1d323cbe6bfb027d3bee6532e5


dev_dependencies:

  build_runner: ^0.8.8
  build_web_compilers: ^0.4.0
  build_test: ^0.10.2

  test: any
  args: any
  material_icons: any
  grinder: any
  mdl_grinder:
    git:
      url: git://github.com/dudochkin-victor/dart-mdl-grinder.git
      ref: 2451be10098202d06c083966296e341982f36a69

    # path: /Volumes/Daten/DevLocal/DevDart/MaterialGrinder

transformers:
#  - di
  - mdl

#  - $dart2js:
#      commandLineOptions: [--enable-experimental-mirrors]


